### ISSUE TITLE
Need length of array for loop output

### ISSUE THREAD

**Issue by webees** [memotype/bj.sh#1]
awesome!

The processing speed is the fastest!

The code logic is hard to understand, can you add comments? Thank you.

Array out of bounds also returns data. If it returns empty, it can also loop.

How do you understand these variables?
```
  local j=$1 # JSON
  local v # value
  local k # key
  local n
  local i 
  local q
  local ol
  local l
  local b1 # { brackets 1
  local b2 # } brackets 2
```

Currently it can only iterate through the array like this and jump out。
Jumps out if the new flag is equal to the old flag.
```
  for((i = 0, old_flag;; i++)); do
    flag=$(bj "$json" $i flag)
    if [[ $flag== $old_flag]]; then break; fi
  done
```

**Comment by memotype** [comment]
Thanks for the feedback. The reason for the short variable names is because a big part of the motivation for this was to make something that could be condensed to be as small as possible to make it easily embedded in scripts for cases where external dependencies are a problem (the `bj-short.sh` version).

Anyway, I'll add some comments and try to fix the array issue.
